# Generated by Django 6.0.2 on 2026-02-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MATH', 'Mathematics'), ('PHY', 'Physics'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('ENG', 'English'), ('HIST', 'History'), ('GEO', 'Geography'), ('ECON', 'Economics'), ('COMM', 'Commerce'), ('PE', 'Physical Education'), ('ART', 'Arts'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
