# Generated by Django 6.0.2 on 2026-02-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_classsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='monitoring_resumption_count',
            field=models.IntegerField(default=1),
        ),
    ]
